# Generated by Django 4.1.3 on 2022-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.IntegerField(),
        ),
    ]
