# Generated by Django 4.1.3 on 2022-12-05 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0002_alter_familiar_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
