# Generated by Django 4.1.3 on 2022-12-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0003_remove_familiar_nacimiento_familiar_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha',
        ),
    ]
